title: Jekyll-Foundation Template
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter: jekyllrb
github:  jekyll
email: james.lane.conkling@gmail.com
author:
location:
keywords:
year:
analytics:

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: :compressed
